abstract class KoranAppStates {}
class initialState extends KoranAppStates{}
class ChangeBottomNav extends KoranAppStates{}
class LoadingSactionLoadingState extends KoranAppStates{}
class LoadingSactionSuccessState extends KoranAppStates{}
class LoadingSactionErrorState extends KoranAppStates{}
class LoadingDetailsLoadingState extends KoranAppStates{}
class LoadingDetailsSucessState extends KoranAppStates{}
class LoadingDetailsErrorState extends KoranAppStates{}
class LoadingKoranLoadingState extends KoranAppStates{}
class LoadingKoranSucessState extends KoranAppStates{}
class LoadingKoranErrorState extends KoranAppStates{}
class increase extends KoranAppStates{}